### ISSUE TITLE
Make exporting of Exodus files optional

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#27]
Currently if PV is not installed on the system the NodeGossiper fails.

**Comment by yaleLeeNGA** [comment]
Pushed first version. Works locally so creating PR.

**Comment by yaleLeeNGA** [comment]
May require to apply preamble coloring afterwards.

**Comment by ppebay** [comment]
I now suggest that Exodus files be turned **OFF** by default. A command line flag should be used to specify the prefix of the Exodus output if and only if such an output is desired.

**Comment by yaleLeeNGA** [comment]
N.B.: commit 4c37031 has been superseded by commit  3114a3f

**Comment by yaleLeeNGA** [comment]
Reopening this issue because I am not sure [this](https://github.com/DARMA-tasking/LB-analysis-framework/pull/40/commits/dacb1739c060174e8bb2df3af355a2f0c4be541b) commit has the expected behavior.  

The idea was to add a `-e` command to specify the name of the visualization files to be generated. Parsing this option as a boolean suppresses the possibility to name those artefacts with a different name than the one automatically generated for the ExodusII file, which tend to be confusing.  
If a dichotomic behavior is expected for viz artefacts generation, a solution would be to add a dedicated boolean attribute which value depends on the parsed value of expected viz file name.

**Comment by ppebay** [comment]
Validating new behavior
