### ISSUE TITLE
Make configuration validation for YAML files less painful to update

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#336]
Right now, it requires a lot of changes in multiple files when a key is changed.

**Comment by tlamonthezie** [comment]
@lifflander, @ppebay  

1. Could you please give me an example scenario of a change ?
This is the main point: when the configuration schema changes, which files do you change and then which ones need to be updated. Do you first the `ConfigurationValidator` ?

We can envisage different possibilities:
- What about some python script to analyze the changed schema and list the files that needs to update (`data/configuration_examples/*.yaml`, `src/lbaf/Applications/*.yaml`, `test/data/config/*.yaml`, and maybe classes to update...)
- We coul also tag each yaml configuration file with some version number that can help to list the files that needs to be updated (for yaml files). This current version number could be defined at the `ConfigurationValidator` level.
The discussion is open...

3. The following might be linked to this issue: in the `internalParameters` class (`LBAF_app.py`) there is some kind of duplication of the allowed keys. When defining a new key in `ConfigurationValidator` we need also to define it in `internalParameters` (for keys at root level). I think we can avoid that.

4. Some pylint errors appears in the 'internalParameters' class like the following I don(t know if it can help but it will be good
`src/lbaf/Applications/LBAF_app.py:179:43: E1101: Instance of 'internalParameters' has no 'n_ranks' member (no-member)`

**Comment by ppebay** [comment]
Thanks for the detailed question @tlamonthezie 
Regarding 1.: try for instance to add one keyword parameter to `conf.yaml`, for instance `foo: bar`. You should see the error it's causing in the configuration validator.

Regarding 3. I agree, there is some redundancy there which I had noticed before and was curious about. It should be eliminated, that said I am not sure where it's best to leave it, either in `LBAF_app.py` or in the configuration validator. Thoughts?

4. Yes please feel free to clean up these issues when you encounter them.


Thanks!

**Comment by tlamonthezie** [comment]
@ppebay thank you for your response.

He is a more advanced analysis:

## Scenarios
Considering that at first we edit `conf.yaml` to defie a change in the schema

### Scenario 1 : add new key##
1. You get a `SchemaError` when running the app. This is good because the configuration does not match the schema (and the schema defines the allowed structure).
2. Then you will update the schema in the `ConfigurationValidator` to setup the key specifications inside the schema - and if root key add to allowed config keys in `internalParameters`  - to resolve this error _
3.a The key is optional : it works immediately
3.b The key is required : we have to check all yaml files that should be valid but are no more valid because of this new key*

### Scenario 2 : remove a required key
1. You get a `SchemaError` when running the app. This is good because the configuration does not match the schema (and the schema defines the allowed structure).
2. Then you will update the schema in the `ConfigurationValidator` to remove the key or make it optional
3. Because this key was propably used by some classes we need to identify the classes where it this key is referenced from
(In general we just search the key in all files to remove its usage)
4. The key is required : we have to check all yaml files that should be valid but are no more valid because of this new key*

### Other scenarios
I think there are also different possible scenarios like adding an option to a list of possible choices or changing a type... but we will go to more complex things I think.

_*Valid yaml files as I know are located in
- `data/configuration_examples/*.yaml`
- `src/lbaf/Applications/*.yaml`
- `test/data/config/**_correct_*.yaml`_

## Possible solution

For all scenarios I think we can develop some **bulk upgrade script** for YAML files
When you have changed `conf.yaml` and the schema in `ConfigurationValidator` , you could then run this script with commands like these ones to propagate the changes to YAML files you want :
`python schema_upgrade add --key=foo --value=bar --targets=all`
`python schema_upgrade remove --key=foo --targets=standard,examples,tests`
where targets indicates what files to upgrade with some meaning (standard, examples, tests, tests-correct, tests-incorrect, all...)

I think that we should be able - with Python - to load edit and **re-write yaml files**.
@ppebay Do you think this kind of solution can help ?

**Comment by ppebay** [comment]
I wholly support your proposed approach @tlamonthezie 
Please go for it. 

Thanks!

**Comment by tlamonthezie** [comment]
> I wholly support your proposed approach @tlamonthezie Please go for it.
> 
> Regarding the "other scenarios", I am also confused by the fact that valid YAML files are located in too many different places. For instance I don't know why we would have some under `test/data` and others under `data` I think those should be consolidated in a single place.
> 
> Meanwhile, does in `Applications` are mostly there for development purposes, but I am thinking that they should probably not even be pushed to the repo.
> 
> Thanks!

I agree that it is not good to have so many different locations for config files and that it would be better to have in one place
I suggest to create a unique `config` directory (at repository root) with the following sub directories:
- `test`
- `dev`
- `examples`
what do you think ?

**Comment by tlamonthezie** [comment]
> > I wholly support your proposed approach @tlamonthezie Please go for it.
> > Regarding the "other scenarios", I am also confused by the fact that valid YAML files are located in too many different places. For instance I don't know why we would have some under `test/data` and others under `data` I think those should be consolidated in a single place.
> > Meanwhile, does in `Applications` are mostly there for development purposes, but I am thinking that they should probably not even be pushed to the repo.
> > Thanks!
> 
> Regarding the script the development is done. The only thing is that we will loose comments in yaml file. Except the logical sections like '# Specify algorithm' that are kept with the addition of some meta-group configurationValidator for root keys. But the good thing is that config files will be homogenized with a clear code.
> 
> I agree that it is not good to have so many different locations for config files and that it would be better to have in one place I suggest to create a unique `config` directory (at repository root) with the following sub directories:
> 
> * `tests`
> * `dev`
> * `examples`
>   _Some are currently in `data`  directory but I think it is should be considered as config instead of data because data is stored as json files and it is not the same thing even if the configuration file can reference data_
> 
> what do you think ?

Finally we will keep 2 configuration directories but it will be also more readable
- /config (new directory) for runnable configurations
- /tests/config for configurations used only for unit tests 
It makes sense to have a config directory in the tests directory (because thie objective of these files are different. All test data is also inside the test directory so all test assets reside under the tests directory. Furthermore these configurations enables to test the schema validator.)
