### ISSUE TITLE
Fix terminal background option in configuration file

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#347]
The `terminal_background` option is not portable. We need to find a better solution.

**Comment by tlamonthezie** [comment]
Currently the `terminal background` is used by the logger to set a specific fore color for the message
The `light` option tells to write messages in `black`
The `dark` option tells to write messages in `light white`
The problem is it is defined in configuration file and can change across different config files. BUT the user's terminal color scheme does not change and maybe only light (or only dark) are readable for this user.

To resolve the I see 2 possibilities:
- set this  option in a global configuration file or in a user settings file
- or just remove the option (and let user's terminal set the default text color for the message)
@ppebay What are your opinion on that ? What is the reason of using a specific message color ?

**Comment by ppebay** [comment]
Thanks @tlamonthezie 

Let us do the **second** option you suggested above -- and have the correct background set based on the environment that can be detected by LBAF.

**Comment by tlamonthezie** [comment]
> Thanks @tlamonthezie
> 
> Let us do the **second** option you suggested above -- and have the correct background set based on the environment that can be detected by LBAF.

Ok we will remove the `terminal_background` option and let the host machine render the log messages.
