### ISSUE TITLE
Create test case for clustering transfer strategy

### ISSUE THREAD

**Issue by cwschilly** [DARMA-tasking/LB-analysis-framework#480]
At present, tests do not reach lines 153-196 of the clustering transfer strategy (`lbsClusteringTransferStrategy.py`):
```python
# Iterate over subclusters only when no swaps were possible
      for o_src in self.__build_rank_subclusters(
              self.__build_rank_clusters(r_src, False).values(), r_src.get_load()):

      # ...
      # ...

      # Report on new load and exit from rank
      self._logger.debug(
          f"Rank {r_src.get_id()} load: {r_src.get_load()} after {self._n_transfers} object transfers")

```

We need to draw up a test case so that no swaps are possible.

This is related to improving test coverage in PR #462 (issue #461).

**Comment by ppebay** [comment]
Here is a proposed test case @cwschilly (simpler ones are possible but this one has a "small trick" into it due to a possible tie when breaking the cluster(s), hence making it a bit more challenging for the algorithm to find the optimal).

* List of objects with their IDs, loads, and memory blocks (all object memory fooprints set to 1):
  * (0, 89, 0)
  * (1, 1, 0)
  * (2, 9, 1)
  * (3, 94, 2)
  * (4, 1, 2)
  * (5, 6, 3)
  
**N.B. 1:** There are only 4 memory blocks, 2 of which are shared by 2 objects, and the 2 others are only "shared" by a single object. As a result these 6 objects will be clustered into 4 memory-block clusters. Each block can be made to have a unit footprint, for this test case this will be inconsequential

* Initial configuration:
  * rank 0: objects with IDs 0, 1, and 2;
  * rank 1: objects with IDs 3, 4, and 5.

**N.B. 2:** problem should be set with a total memory constraint high enough to make sure it never kicks in (e.g. 10 or more). Initial load balance is: 99 on rank 0 and 101 on rank 1. **NO** cluster swap should occur and code should thus directly jump into the sub-clustering stage. Optimal load-imbalance (=0) should be found in a single iteration.

Other practical considerations: number of information rounds can be made at k=1, and fanout f=1 as well, this is sufficient. Only a couple of iterations (i=2) should suffice to find the solution with the clustering-based strategy.

@cwschilly

**Comment by cwschilly** [comment]
Thank you @ppebay !

**Comment by ppebay** [comment]
Additional note: the "home ID" of the block must be set to the same value as that of the rank to which it is initially assigned.
